### ISSUE TITLE
Organize teams in FOSSRIT organization

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#12]
This issue is about how the current team setup in the FOSSRIT organization is laid out. It's a little bit messy right now and disorganized. The following proposal details what would be best to make the hierarchy more organized and also make it useful for later reference.

# Sorting by year
The first suggestion is organizing all of the teams by graduation year, e.g. "Class of 2014", "Class of 2015", etc.). This would organize the teams and make it easier to search through them. It also comes with the benefit of sorting members of the FOSSRIT organization by graduation year. This could be useful for later reference as well.

# Removing teams from old projects
Teams that are for projects no longer under active development should be removed, and the students in those teams moved to teams sorted by graduation year.

# Removing teams with five or less people
Teams for projects under active development but have less than five people should be converted to the teams based on graduation year as well.

**Comment by liam-middlebrook** [comment]
I don't see any benefit from removing old teams other than to reorganize by year. Is there anything I'm missing?

**Comment by jflory7** [comment]
@liam-middlebrook Removing the smaller, older teams would mostly be to help clean up the teams and make them easier to view with the new GitHub organization structure. Teams could be publicized and it would be easier to sort through for org admins, in my opinion.

**Comment by msoucy** [comment]
The yacht is dead long live the yacht

**Comment by jflory7** [comment]
Some more developments happened based on in-person discussions that happened in FOSShours today. For future reference, I'm going to explain what was done and why.


## New teams created

As of now, there are teams for each graduating class from 2016 and beyond. All other students, faculty, or other person associated with the FOSSBox / FOSS@MAGIC before that point is placed in the OGs team (with some exceptions for those already in the team). The new team structure isn't used for permissions as much as organization of students based on their graduation year. This makes it easier to sort existing members of the organization, understand their timeframe at RIT, and also making it easier to get an idea of whether or not a contributor is currently on campus or moved on to new and other exciting placed.


## Old teams cleaned

To help tidy the existing teams into something more easily readable, all teams with either a small number of members OR with permissions for 1-2 repos were migrated from a team to having individual permissions on a repo-by-repo basis. Due diligence was used when migrating permissions, so any contributor for the FOSSRIT org should not notice any difference in what repositories they had access to compared to what they have access to now. The change was purely aesthetic.

In the event that I did miss someone, they can file an issue here, ask in IRC, or even email someone if needed to gain access. Ideally, it shouldn't be hard to fix a missed permission if there was anyone that was accidentally skimped. If anyone did lose access to a repo, it was accidental.


## New owners added

Two new owners are added to the repo, @ritjoe and @schneidy. Dan Schneiderman (schneidy) is the new FOSS@MAGIC Research Associate & Community Liaison at RIT and D. Joe (ritjoe) is a current professor teaching the HFOSS course. Granting these permissions allows them to have better control over creating repos, promoting them at events, being used as a learning tool for classes, or modifying existing tools and resources for classes, events, or otherwise.


----


This all probably sounds over-formalized, and it probably is, but I want to make it clear **what** happened and **why**, so if any questions are asked later, this can be a quick frame of reference.

**Comment by decause** [comment]
On May 17, 2016 21:10, "Justin W. Flory" <notifications@github.com> wrote:
>
> Some more developments happened based on in-person discussions that
happened in FOSShours today. For future reference, I'm going to explain
what was done and why.
>
> New teams created
>
> As of now, there are teams for each graduating class from 2016 and
beyond. All other students, faculty, or other person associated with the
FOSSBox / FOSS@MAGIC before that point is placed in the OGs team (with some
exceptions for those already in the team). The new team structure isn't
used for permissions as much as organization of students based on their
graduation year. This makes it easier to sort existing members of the
organization, understand their timeframe at RIT, and also making it easier
to get an idea of whether or not a contributor is currently on campus or
moved on to new and other exciting placed.
>
> Old teams cleaned
>
> To help tidy the existing teams into something more easily readable, all
teams with either a small number of members OR with permissions for 1-2
repos were migrated from a team to having individual permissions on a
repo-by-repo basis. Due diligence was used when migrating permissions, so
any contributor for the FOSSRIT org should not notice any difference in
what repositories they had access to compared to what they have access to
now. The change was purely aesthetic.
>
> In the event that I did miss someone, they can file an issue here, ask in
IRC, or even email someone if needed to gain access. Ideally, it shouldn't
be hard to fix a missed permission if there was anyone that was
accidentally skimped. If anyone did lose access to a repo, it was
accidental.
>
> New owners added
>
> Two new owners are added to the repo, @ritjoe and @schneidy. Dan
Schneiderman (schneidy) is the new FOSS@MAGIC Research Associate &
Community Liaison at RIT and D. Joe (ritjoe) is a current professor
teaching the HFOSS course. Granting these permissions allows them to have
better control over creating repos, promoting them at events, being used as
a learning tool for classes, or modifying existing tools and resources for
classes, events, or otherwise.
>
> ________________________________
>
> This all probably sounds over-formalized, and it probably is, but I want
to make it clear what happened and why, so if any questions are asked
later, this can be a quick frame of reference.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

+1

Nice work jflory7 with the housekeeping.
